### ISSUE TITLE
Split resources into to "tools" and "science" 

### ISSUE THREAD

**Issue by ergonyc** [ndcn/self-guided-learning#2]
EDIT Jan 23,23:

As a top-level organizational principle something like:

- tools: 
   - tools: python, R, snakemake, git/github
   - frameworks: open science, opensource

- science: various analyses
  - singlecell etc

**Comment by cjsifuen** [comment]
Where would best practices in open science and data science fall into here?

**Comment by ergonyc** [comment]
Here's how I might suggest overall organization... landing page explains the overall idea and contains a couple "top links" for a reader to begin their journey, and explains the overall organization.  i.e.  a collection of RESOURCES organized into Tools (things) & Frameworks (approaches) plus an overall aggregation of  entry point TUTORIALS.  Eventually I think there would be a section on the "modern science notebook" (discussed in issue #3)   
Then the tabs would be split into:
-TOOLS
-FRAMEOWRKS
-INDEX

something like this:
self-guided-learning
|- Overview / Principles (home page prose)
  |- Open Science principles.  reproducibility, harmonization, scalability
  |- link to first "getting started"
  |- repo organization explanation: 
|- Resources 
    |- 1. Tools (links to entry points / about / gettin started)
       |- software, coding (python, R, snakemake, SQL, bigQuery) 
       |- source / version control (Git/Github)
       |- jupyter notebooks
    |- 2. Frameworks / Best-practices (links to articles / repos / etc)
      |- Open Science
      |- open source
      |- reproducibility / scalabily
      |- science analyses/technique
         |- single cell
         |- GWAS 
         |- etc    
  |- index of Tutorials (links to how-to/ tutorials / courses)
    |- software
    |- coding
    |- git/github
    |- etc
 |-  [modern scientific notebook 101] to be curated / articulated

**Comment by cjsifuen** [comment]
I like the line of thought here, but I'm still having a hard time coming up with a clear separation for some things. 

I'm not seeing the difference in the index and other tutorials. So the tutorials for each thing (which is mostly what the resources are likely to be) will live in two places?

Is the index just meant as a quick way to search through the resources?

**Comment by ergonyc** [comment]
I was thinking separating links to downloads with links which are spcifically "tutorial".  I really like this [framework](https://diataxis.fr/_images/diataxis.png)

**Comment by ergonyc** [comment]
Also, I edited the original "issue" copy.  I think its clearer to define "frameworks" as conceptual things, and "tools" as software.  And then to have another "science" category which are tools & frameworks specifically around biology / bioinformatics

**Comment by cjsifuen** [comment]
> I was thinking of separating links to downloads with links that are specifically "tutorial". Actually, as I [edited above] I think LEARNING RESOURCES as you originally had, and maybe (OTHER?) RESOURCES separated into TOOLS and FRAMEWORKS would be good.
> 
> I really like this [framework](https://diataxis.fr/#)
> 
> [diagram] (https://diataxis.fr/_images/diataxis.png)

I really like the way this is framed also. We should definitely figure out a way to break it down like this, possibly with tags or something?

I'm wondering if keeping things together at first and having general categories is better? I worry about people getting lost while looking for things.

**Comment by cjsifuen** [comment]
Okay, what about

- learning resources -- tutorials, courses, and how-to: for learning about general bioinformatics, reproducibility, open source practices, data visualizations, single-cell analyses, proteomics, imaging and segmentation, etc.
- tools -- a curated set of resources/libraries for use in plotting, python, single-cell analysis, segmentation, biologically relevant ML, etc?

Each resource page would be broken up into categories that we would create. My ultimate goal is to create a sort of list (with yaml input format) to make it easily updatable. Each resource entry would have a name, description, link, and tags/categories. Then quarto would automatically create a list that could be searchable and filterable based upon the tags.

**Comment by ergonyc** [comment]
I started to instantiate this here: https://ergonyc.github.io/self-guided-learning/

It's a fork from your repo which also has the github actions working for automatically rendering the site with quarto when the `main` branch gets update.  I'll do a pull request from my fork for reference, but I'm not sure you really want to merge it.

**Comment by cjsifuen** [comment]
Design question underlying this issue was addressed.
